### ISSUE TITLE
Project Files not rendering

### ISSUE THREAD

**Issue by erdemkosk** [z3by/vuepress-blog-template#2]
There is no project files like _projects so how can ı render ? 
<img width="1424" alt="Ekran Resmi 2020-02-10 15 57 34" src="https://user-images.githubusercontent.com/8267466/74151850-1a2b5a00-4c1e-11ea-80fa-77c30546869f.png">

**Comment by z3by** [comment]
Thanks, @erdemkosk I just updated this template, it was a little bit out of date.

**Comment by z3by** [comment]
I updated the template @erdemkosk

**Comment by erdemkosk** [comment]
Thanks for it @zb3y . If u want to checkout template that ı am using now [mywebsite with using this template](http://erdemkosk.com)

**Comment by z3by** [comment]
look very nice! I like the about page!
